# Generated by Django 4.2.1 on 2023-05-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment_Account",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("balance", models.IntegerField()),
                ("order_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("user_id_number", models.IntegerField()),
                ("user_phone", models.IntegerField()),
                ("user_email", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment_invoice",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("aid", models.IntegerField()),
                ("Price", models.IntegerField()),
                ("Key", models.CharField(max_length=50)),
                ("order_id", models.IntegerField()),
                ("invoice_id", models.IntegerField(verbose_name=50)),
                ("airline", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Payment_order",
            fields=[
                (
                    "payment_order_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("invoice_time", models.DateTimeField()),
                ("invoice_description", models.CharField(max_length=50)),
                ("Price", models.IntegerField()),
                ("status", models.IntegerField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.payment_account",
                    ),
                ),
            ],
        ),
    ]
