# Generated by Django 4.2.1 on 2023-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_payment_account_user_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment_order",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
